mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'(?P<pk>\d+)/$', views.DetailView.as_view(), name='details'),
    url(r'(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from polls.models import Poll, Choice
from django.views import generic

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_poll_list"

    def get_queryset(self):
        """Return the last five published polls"""
        return Poll.objects.order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Poll
    template_name = "polls/details.html"

class ResultsView(generic.DetailView):
    model = Poll
    template_name = "polls/results.html"

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk = poll_id)

    try:
        selection = p.choice_set.get(pk = request.POST['choice'])
    except KeyError, Choice.DoesNotExist:
        return render(request, 'polls/details.html', {
            'poll': p,
            'error_message': "PICK SOMETHING, ASSHOLE"
        })
    else:
        selection.votes += 1
        selection.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite/polls/templates/polls/details.html
<h1>Poll: {{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
  {% csrf_token %}
  {% for choice in poll.choice_set.all %}
     <input type="radio" name="choice" value="{{ choice.id }}"
            id="choice_{{ forloop.counter }}"/>
     <label for="choice_{{ forloop.counter }}">{{ choice.choice_text }}</label>
     <br/>
  {% endfor %}
     <input type="submit" value="Vote"/>
</form>
<p><a href="{% url 'polls:index' %}">Back to polls</a></p>

mysite/polls/templates/polls/index.html
<h1>Polls!</h1>
{% if latest_poll_list %}
<ul>
  {% for poll in latest_poll_list %}
    <li><a href="{% url 'polls:details' poll.id %}">{{ poll.question }}</a>  (created {{ poll.pub_date }})</li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>Poll: {{ poll.question }}</h1>

<table>
<thead><tr><th>Choice</th><th>Votes</th></tr></thead>
<tbody>
{% for choice in poll.choice_set.all %}
<tr><td>{{ choice.choice_text }}</td><td>{{ choice.votes }}</td></tr>
{% endfor %}
</tbody>
</table>